name: Build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: build
        run: ./gradlew build --no-daemon
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            build/libs/
            module/**/build/libs/
      - name: capture test reports on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Logs
          path: |
            build/reports
            modules/**/build/reports
